services:
  - type: web
    name: apiagrobot
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
    healthCheckPath: /health

